services:
  first-class:
    build:
      context: ./client
    image: first-class-awnings_first-class   # 👈 ADD THIS
    container_name: first-class
    env_file:
      - ./client/.env
    ports:
      - "4000:3000"
    restart: unless-stopped