version: "3.8"

services:
  first-class:
    build:
      context: ./client
      dockerfile: Dockerfile   # optional if it's named Dockerfile
    container_name: first-class
    env_file:
      - ./client/.env
    ports:
      - "4000:3000"
    restart: unless-stopped